[book]
authors = ["Henri Joel Sedjame"]
language = "en"
multilingual = false
src = "src"
title = "edgedb-query documentation"

[rust]
edition  = "2018"

[build]
build-dir = "book"
create-missing = true
use-default-preprocessors = true

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"

[output.html.playground]
editable = true
copyable = true
runnable = false
line-numbers = true