name: Test edgedb-query-derive libe

on:
  push:
    branches:
      - main
      - feature/*

jobs:

  tests:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: cd edgedb-query-derive && cargo test --test lib_tests

